//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tropical.Infrastructure.ControleAcesso {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ControleAcesso.ControleAcessoSoap")]
    public interface ControleAcessoSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Tropical.Infrastructure.ControleAcesso.HelloWorldResponse HelloWorld(Tropical.Infrastructure.ControleAcesso.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name idLdap from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChecaPermissaoPorFuncionalidade", ReplyAction="*")]
        Tropical.Infrastructure.ControleAcesso.ChecaPermissaoPorFuncionalidadeResponse ChecaPermissaoPorFuncionalidade(Tropical.Infrastructure.ControleAcesso.ChecaPermissaoPorFuncionalidadeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Tropical.Infrastructure.ControleAcesso.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Tropical.Infrastructure.ControleAcesso.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tropical.Infrastructure.ControleAcesso.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Tropical.Infrastructure.ControleAcesso.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChecaPermissaoPorFuncionalidadeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChecaPermissaoPorFuncionalidade", Namespace="http://tempuri.org/", Order=0)]
        public Tropical.Infrastructure.ControleAcesso.ChecaPermissaoPorFuncionalidadeRequestBody Body;
        
        public ChecaPermissaoPorFuncionalidadeRequest() {
        }
        
        public ChecaPermissaoPorFuncionalidadeRequest(Tropical.Infrastructure.ControleAcesso.ChecaPermissaoPorFuncionalidadeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChecaPermissaoPorFuncionalidadeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idLdap;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string funcionalidadeSigla;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ipClient;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string mensagemDeErroParam;
        
        public ChecaPermissaoPorFuncionalidadeRequestBody() {
        }
        
        public ChecaPermissaoPorFuncionalidadeRequestBody(string idLdap, string funcionalidadeSigla, string ipClient, string mensagemDeErroParam) {
            this.idLdap = idLdap;
            this.funcionalidadeSigla = funcionalidadeSigla;
            this.ipClient = ipClient;
            this.mensagemDeErroParam = mensagemDeErroParam;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChecaPermissaoPorFuncionalidadeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChecaPermissaoPorFuncionalidadeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tropical.Infrastructure.ControleAcesso.ChecaPermissaoPorFuncionalidadeResponseBody Body;
        
        public ChecaPermissaoPorFuncionalidadeResponse() {
        }
        
        public ChecaPermissaoPorFuncionalidadeResponse(Tropical.Infrastructure.ControleAcesso.ChecaPermissaoPorFuncionalidadeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChecaPermissaoPorFuncionalidadeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ChecaPermissaoPorFuncionalidadeResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mensagemDeErroParam;
        
        public ChecaPermissaoPorFuncionalidadeResponseBody() {
        }
        
        public ChecaPermissaoPorFuncionalidadeResponseBody(bool ChecaPermissaoPorFuncionalidadeResult, string mensagemDeErroParam) {
            this.ChecaPermissaoPorFuncionalidadeResult = ChecaPermissaoPorFuncionalidadeResult;
            this.mensagemDeErroParam = mensagemDeErroParam;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ControleAcessoSoapChannel : Tropical.Infrastructure.ControleAcesso.ControleAcessoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ControleAcessoSoapClient : System.ServiceModel.ClientBase<Tropical.Infrastructure.ControleAcesso.ControleAcessoSoap>, Tropical.Infrastructure.ControleAcesso.ControleAcessoSoap {
        
        public ControleAcessoSoapClient() {
        }
        
        public ControleAcessoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ControleAcessoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControleAcessoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControleAcessoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tropical.Infrastructure.ControleAcesso.HelloWorldResponse Tropical.Infrastructure.ControleAcesso.ControleAcessoSoap.HelloWorld(Tropical.Infrastructure.ControleAcesso.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Tropical.Infrastructure.ControleAcesso.HelloWorldRequest inValue = new Tropical.Infrastructure.ControleAcesso.HelloWorldRequest();
            inValue.Body = new Tropical.Infrastructure.ControleAcesso.HelloWorldRequestBody();
            Tropical.Infrastructure.ControleAcesso.HelloWorldResponse retVal = ((Tropical.Infrastructure.ControleAcesso.ControleAcessoSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tropical.Infrastructure.ControleAcesso.ChecaPermissaoPorFuncionalidadeResponse Tropical.Infrastructure.ControleAcesso.ControleAcessoSoap.ChecaPermissaoPorFuncionalidade(Tropical.Infrastructure.ControleAcesso.ChecaPermissaoPorFuncionalidadeRequest request) {
            return base.Channel.ChecaPermissaoPorFuncionalidade(request);
        }
        
        public bool ChecaPermissaoPorFuncionalidade(string idLdap, string funcionalidadeSigla, string ipClient, ref string mensagemDeErroParam) {
            Tropical.Infrastructure.ControleAcesso.ChecaPermissaoPorFuncionalidadeRequest inValue = new Tropical.Infrastructure.ControleAcesso.ChecaPermissaoPorFuncionalidadeRequest();
            inValue.Body = new Tropical.Infrastructure.ControleAcesso.ChecaPermissaoPorFuncionalidadeRequestBody();
            inValue.Body.idLdap = idLdap;
            inValue.Body.funcionalidadeSigla = funcionalidadeSigla;
            inValue.Body.ipClient = ipClient;
            inValue.Body.mensagemDeErroParam = mensagemDeErroParam;
            Tropical.Infrastructure.ControleAcesso.ChecaPermissaoPorFuncionalidadeResponse retVal = ((Tropical.Infrastructure.ControleAcesso.ControleAcessoSoap)(this)).ChecaPermissaoPorFuncionalidade(inValue);
            mensagemDeErroParam = retVal.Body.mensagemDeErroParam;
            return retVal.Body.ChecaPermissaoPorFuncionalidadeResult;
        }
    }
}
